export const listings = [
  {
    id: 'central',
    title: '전농 센트럴 오피스텔',
    summary: '신축급 오피스텔로 풀옵션 완비. 회기역 도보 8분, 채광 좋은 남향 구조입니다.',
    dealType: '월세',
    deposit: '500',
    rent: '45',
    address: '전농동 345-67',
    walkingMinutes: 7,
    distance: '520m',
    position: { left: '30%', top: '28%' },
    safetyScore: 8.5,
    marketDiff: '-5%',
    marketPrice: '48만원',
    area: '23㎡ (7평)',
    supplyArea: '31㎡ (9평)',
    floor: '3층 / 5층',
    maintenance: '매월 5만원',
    buildingType: '오피스텔(분리형 1.5룸)',
    features: ['신축급', '풀옵션', 'CCTV', '엘리베이터'],
    reviews: 8,
    rating: 4.5,
    agent: { name: '김철수', office: '전농공인중개사무소', license: '경력 12년 · 서울 제12345호' },
    risk: { level: '안전', mortgage: '없음', ratio: '62%', lh: '가능', hug: '확인 필요' },
  },
  {
    id: 'remodeling',
    title: '리모델링 원룸',
    summary: '조용한 주택가의 리모델링 원룸. 학교와 가까워 통학이 편리합니다.',
    dealType: '월세',
    deposit: '1,000',
    rent: '50',
    address: '전농동 345-67',
    walkingMinutes: 5,
    distance: '390m',
    position: { left: '57%', top: '50%' },
    safetyScore: 9.2,
    marketDiff: '-8%',
    marketPrice: '54만원',
    area: '26㎡ (8평)',
    supplyArea: '33㎡ (10평)',
    floor: '4층 / 6층',
    maintenance: '매월 7만원',
    buildingType: '오피스텔(분리형 1.5룸)',
    features: ['리모델링', '풀옵션', 'CCTV'],
    reviews: 11,
    rating: 4.8,
    agent: { name: '박민준', office: '시립대공인중개사', license: '경력 15년 · 서울 제34567호' },
    risk: { level: '안전', mortgage: '없음', ratio: '58%', lh: '가능', hug: '가능' },
  },
  {
    id: 'jeonse', title: '햇살 좋은 투룸', summary: '남향 채광과 넉넉한 수납공간을 갖춘 투룸입니다.', dealType: '전세', deposit: '1.2억', rent: null,
    address: '휘경동 221-4', walkingMinutes: 10, distance: '780m', position: { left: '24%', top: '56%' }, safetyScore: 7.8, marketDiff: '-2%', marketPrice: '1.25억', area: '38㎡ (11평)', supplyArea: '43㎡ (13평)', floor: '2층 / 4층', maintenance: '매월 4만원', buildingType: '다세대주택', features: ['투룸', '남향'], reviews: 4, rating: 4.1, agent: { name: '이수진', office: '회기공인중개사무소', license: '서울 제22345호' }, risk: { level: '보통', mortgage: '확인 필요', ratio: '71%', lh: '가능', hug: '확인 필요' },
  },
  {
    id: 'studio', title: '캠퍼스 뷰 원룸', summary: '대학가 인접, 관리가 잘 된 밝은 원룸입니다.', dealType: '월세', deposit: '300', rent: '40',
    address: '전농동 104-8', walkingMinutes: 6, distance: '460m', position: { left: '40%', top: '18%' }, safetyScore: 8.9, marketDiff: '-3%', marketPrice: '42만원', area: '20㎡ (6평)', supplyArea: '24㎡ (7평)', floor: '5층 / 5층', maintenance: '매월 4만원', buildingType: '원룸', features: ['풀옵션', '옥상'], reviews: 6, rating: 4.4, agent: { name: '김철수', office: '전농공인중개사무소', license: '서울 제12345호' }, risk: { level: '안전', mortgage: '없음', ratio: '55%', lh: '가능', hug: '가능' },
  },
  {
    id: 'budget', title: '가성비 분리형 원룸', summary: '합리적인 월세와 깔끔한 내부가 장점인 매물입니다.', dealType: '월세', deposit: '700', rent: '38',
    address: '이문동 19-4', walkingMinutes: 12, distance: '900m', position: { left: '67%', top: '68%' }, safetyScore: 8.1, marketDiff: '-6%', marketPrice: '41만원', area: '21㎡ (6평)', supplyArea: '26㎡ (8평)', floor: '2층 / 4층', maintenance: '매월 3만원', buildingType: '원룸', features: ['분리형', '반려동물 협의'], reviews: 5, rating: 4.2, agent: { name: '오민지', office: '이문공인중개사무소', license: '서울 제73456호' }, risk: { level: '안전', mortgage: '없음', ratio: '60%', lh: '가능', hug: '가능' },
  },
];

export const reviews = [
  { id: 1, name: '박*준', initial: '박', rating: 5, period: '8개월 거주 · 2024.12', text: '주변에 편의점·식당 많아서 자취 생활하기 편해요. CCTV 있어서 밤에도 안심됩니다.' },
  { id: 2, name: '최*은', initial: '최', rating: 4, period: '1년 3개월 거주 · 2024.11', text: '실제 시세보다 저렴하게 나온 매물이라 만족해요. 등기부도 깨끗했습니다.' },
];
